name: Sonar Static Analysis Scan

description: Sonar Static Analysis Scan
  
runs:
  using: 'composite'
  steps:
   - run: |
        echo "GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}"
        echo "SONAR_TOKEN: ${{env.SONAR_TOKEN}}"
     shell: pwsh

   - name: Scan and Publish
     uses: chill-viking/dotnet-sonar-scanner@v2
     with:
        sonar-project-key: 'sandipray63in_WeatherForecastAzureFunctionAndAngularSample'
        sonar-org-key: 'sandipray63in'
        token: ${{ env.GITHUB_TOKEN }}
        sonar-token: ${{ env.SONAR_TOKEN }}
        working-directory: './WeatherForecastAPI'
     
       