name: Sonar Static Analysis Scan

description: Sonar Static Analysis Scan

inputs:
        GITHUB_TOKEN:
           description: 'GitHub Token'
           required: true
        SONAR_TOKEN: 
           description: 'Sonar Token'
           required: true
  
runs:
  using: 'composite'
  steps:
   - run: |
        echo "GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}"
        echo "SONAR_TOKEN: ${{inputs.SONAR_TOKEN}}"
     shell: pwsh

   - name: Scan and Publish
     uses: chill-viking/dotnet-sonar-scanner@v2
     with:
        sonar-project-key: 'sandipray63in_WeatherForecastAzureFunctionAndAngularSample'
        sonar-org-key: 'sandipray63in'
        token: ${{ inputs.GITHUB_TOKEN }}
        sonar-token: ${{ inputs.SONAR_TOKEN }}
        working-directory: './WeatherForecastAPI'
     
       