name: Sonar Static Analysis Scan

description: Sonar Static Analysis Scan
  
runs:
  using: 'composite'
  steps:
   - name: Scan and Publish
     uses: Secbyte/dotnet-sonarscanner@v2.3
     with:
      buildCommand: dotnet build .
      testCommand: dotnet test .
      projectKey: 'sandipray63in_WeatherForecastAzureFunctionAndAngularSample'
      sonarOrganisation: 'sandipray63in'
      beginArguments: >
        /d:sonar.verbose="true"
        /d.sonar.exclusions=WeatherForecastBDD
