name: CI CD Dev
description : CI CD Dev

inputs:
        AZURE_REGION:
           description: 'Azure Region'
           required: true
        RESOURCE_GROUP_NAME: 
           description: 'Resource Group Name'
           required: true
        MSI_NAME: 
           description: 'MSI Name'
           required: true
        MSI_RESOURCE_GROUP: 
           description: 'MSI Resource Group'
           required: true
        APP_NAME_PREFIX:
           description: 'App Name Prefix'
           required: true
        BDD_WORKSPACE_PATH:
           description: 'App Name Prefix'
           required: true
           default: 'WeatherForecastBDD'
        
runs:
    using: 'composite'

    steps:
        - uses: ./.github/actions/ci-build/action.yaml
          with:
            SOLUTION_NAME: 'WeatherForecast'
            TEST_PROJECT_PATH: 'WeatherForecastTDD\WeatherForecastTDD.csproj'

        - uses: ./.github/actions/azure-infra-cicd
          id: azureInfraCICD
          with:
            AZURE_REGION: '${{inputs.AZURE_REGION}}'
            ENVIRONMENT_TYPE: 'dev'
            APP_NAME_PREFIX: '${{inputs.APP_NAME_PREFIX}}'
            RESOURCE_GROUP_NAME: '${{inputs.RESOURCE_GROUP_NAME}}'
            MSI_NAME: '${{inputs.MSI_NAME}}'
            MSI_RESOURCE_GROUP: '${{inputs.MSI_RESOURCE_GROUP}}'

        - uses: ./.github/actions/functions-api-cicd
          with:
            ENVIRONMENT_TYPE: 'dev'
            APP_NAME_PREFIX: '${{inputs.APP_NAME_PREFIX}}'
            RESOURCE_GROUP_NAME: '${{inputs.RESOURCE_GROUP_NAME}}'
            API_NAME: '${{steps.azureInfraCICD.outputs.apiName}}'
            APIM_NAME: '${{steps.azureInfraCICD.outputs.apimName}}'
            FUNCTION_NAME: '${{steps.azureInfraCICD.outputs.functionAppName}}'
            ORIGIN_URL: '${{steps.azureInfraCICD.outputs.staticWebsiteUrl}}'    
            
        - uses: ./.github/actions/spa-cicd
          with: 
            ENVIRONMENT_TYPE: 'dev'
            APP_NAME_PREFIX: '${{inputs.APP_NAME_PREFIX}}'
            RESOURCE_GROUP_NAME: '${{inputs.RESOURCE_GROUP_NAME}}'
            CLIENT_URL: '${{steps.azureInfraCICD.outputs.staticWebsiteUrl}}'
            API_URL: '${{steps.azureInfraCICD.outputs.apiUrl}}'
            API_AUTH_KEY: '${{steps.azureInfraCICD.outputs.authKey}}'
            AZURE_STORAGE_NAME: '${{steps.azureInfraCICD.outputs.staticWebsiteStorageAccountName}}'
            CDN_PROFILE_NAME: '${{steps.azureInfraCICD.outputs.cdnProfileName}}'
            CDN_ENDPOINT_NAME: '${{steps.azureInfraCICD.outputs.cdnEndpointName}}' 
            
        # Set app configurations of Angular
        - name: 'Replace tokens'
          uses: cschleiden/replace-tokens@v1.0
          with:
            tokenPrefix: '__'
            tokenSuffix: '__'
            files: ${{ github.workspace }}/${{ inputs.BDD_WORKSPACE_PATH }}/appConfig.json
          env: 
            weatherForecastAPIUrl: ${{ steps.azureInfraCICD.outputs.apiUrl }}
            authKey: ${{ steps.azureInfraCICD.outputs.authKey }}

        - name: 'BDD Test'
          uses: actions/cryptic-wizard/run-specflow-tests@v1.3.1
          with:
            test-assembly-path: WeatherForecastBDD/bin/Release/netcoreapp3.1
            test-assembly-dll: WeatherForecastBDD.dll
            output-html: WeatherForecastBDD.html