name: CI CD Dev
description : CI CD Dev

inputs:
        GITHUB_TOKEN:
           description: 'GitHub Token'
           required: true
        SONAR_TOKEN: 
           description: 'Sonar Token'
           required: true
        AZURE_CREDENTIALS: 
            description: 'Azure Credentials'
            required: true
        AZURE_REGION:
           description: 'Azure Region'
           required: true
        RESOURCE_GROUP_NAME: 
           description: 'Resource Group Name'
           required: true
        MSI_NAME: 
           description: 'MSI Name'
           required: true
        MSI_RESOURCE_GROUP: 
           description: 'MSI Resource Group'
           required: true
        APP_NAME_PREFIX:
           description: 'App Name Prefix'
           required: true
        BDD_WORKSPACE_PATH:
           description: 'App Name Prefix'
           required: true
           default: 'WeatherForecastBDD'
        
runs:
    using: 'composite'

    steps:

        - uses: ./.github/actions/azure-infra-cicd
          id: azureInfraCICD

        - uses: ./.github/actions/functions-api-cicd
          with:
            API_NAME: '${{steps.azureInfraCICD.outputs.apiName}}'
            APIM_NAME: '${{steps.azureInfraCICD.outputs.apimName}}'
            FUNCTION_NAME: '${{steps.azureInfraCICD.outputs.functionAppName}}'
            ORIGIN_URL: '${{steps.azureInfraCICD.outputs.staticWebsiteUrl}}' 
            
        - uses: ./.github/actions/spa-cicd
          with:
            CLIENT_URL: '${{steps.azureInfraCICD.outputs.staticWebsiteUrl}}'
            API_URL: '${{steps.azureInfraCICD.outputs.apiUrl}}'
            API_AUTH_KEY: '${{steps.azureInfraCICD.outputs.authKey}}'
            AZURE_STORAGE_NAME: '${{steps.azureInfraCICD.outputs.staticWebsiteStorageAccountName}}'
            CDN_PROFILE_NAME: '${{steps.azureInfraCICD.outputs.cdnProfileName}}'
            CDN_ENDPOINT_NAME: '${{steps.azureInfraCICD.outputs.cdnEndpointName}}'
            
        # Set app configurations of Angular
        - name: 'Replace tokens'
          uses: cschleiden/replace-tokens@v1.0
          with:
            tokenPrefix: '__'
            tokenSuffix: '__'
            files: ${{ github.workspace }}/${{ inputs.BDD_WORKSPACE_PATH }}/appConfig.json
          env: 
            weatherForecastAPIUrl: ${{ steps.azureInfraCICD.outputs.apiUrl }}
            authKey: ${{ steps.azureInfraCICD.outputs.authKey }}

        # - name: 'BDD Test'
        #   uses: actions/cryptic-wizard/run-specflow-tests@v1.3.1
        #   with:
        #     test-assembly-dll: WeatherForecastBDD.dll
        #     test-execution-json: TestExecution.json
        #     configuration: Release
        #     output-html: BDDTestResults.html
        #     build-verbosity: normal
        #     test-verbosity: minimal
        #     framework: netcoreapp3.1
        #     no-build: true
        #     logger: trx
        #     logger-file-name: ../../BDDTestResults.trx
        #     upload-artifact: true