parameters:
- name: azureSubscription  
- name: functionAppName
  default: 'WeatherForecastFunc'
- name: package
- name: environment
  default: 'development'

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: '${{ parameters.environment }}'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              appType: functionApp
              appName: ${{ parameters.functionAppName }}
              package: '${{ parameters.package }}'