parameters:
- name: environment
  default: 'development'

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: '${{ parameters.environment }}'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
         steps: 
            - task: AzureStaticWebApp@0
              inputs:
                  app_location: 'src/dist' 
                  app_build_command: 'npm run build'
                  skip_api_build: true
                  cwd: '$(System.DefaultWorkingDirectory)/WeatherForecastUI' # Working directory - optional
                  azure_static_web_apps_api_token: $(deployment_token)
                  build_timeout_in_minutes: 30