name: CI PR Action

on:
  workflow_dispatch:
 
env:
     AZURE_REGION: 'centralindia'
     RESOURCE_GROUP_NAME: 'WeatherForecastRG'
     MSI_NAME: 'WeatherForecastAppMSI'
     MSI_RESOURCE_GROUP: 'WeatherForecastRG'
     APP_NAME_PREFIX: 'WeatherForecast'
      
jobs:
  ci-pr:

    runs-on: windows-latest

    steps:
    # Authentication
    # Set up the following secrets in your repository: AZURE_CREDENTIALS
    # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        environment: 'dev'
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1

    # - uses: ./.github/Workflows/ci-build.yaml
    #   with:
    #      SOLUTION_NAME: 'WeatherForecast'
    #      TEST_PROJECT_PATH: 'WeatherForecastTDD\WeatherForecastTDD.csproj'

    # - uses: ./.github/Workflows/ci-cd-dev.yaml
    #   with:
    #      AZURE_REGION: '${{env.AZURE_REGION}}'
    #      RESOURCE_GROUP_NAME: '${{env.RESOURCE_GROUP_NAME}}'
    #      MSI_NAME: '${{env.MSI_NAME}}'
    #      MSI_RESOURCE_GROUP: '${{env.MSI_RESOURCE_GROUP}}'
    #      APP_NAME_PREFIX: '${{env.APP_NAME_PREFIX}}'

    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()