name: CI PR Action

on:
  workflow_dispatch:
 
env:
     AZURE_REGION: 'centralindia'
     RESOURCE_GROUP_NAME: 'WeatherForecastRG'
     MSI_NAME: 'WeatherForecastAppMSI'
     MSI_RESOURCE_GROUP: 'WeatherForecastRG'
     APP_NAME_PREFIX: 'WeatherForecast'
     ENVIRONMENT_TYPE: 'dev'
     BICEP_FILE_PATH: 'Deploy' 
     SOLUTION_NAME: 'WeatherForecast'
     TEST_PROJECT_PATH: 'WeatherForecastTDD\WeatherForecastTDD.csproj'
     GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
     SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}
     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     DOTNET_VERSION: '3.1.410' 
     FUNCTIONAPP_PATH: 'WeatherForecastAPI'
     ANGULAR_PATH: 'WeatherForecaastUI'
     NODE_VERSION: '14'


jobs:
  ci-pr:

    runs-on: windows-latest

    environment: dev

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
  
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
      with:
        sparse-checkout: |
            .github
            Deploy
            WeatherForecastAPI
            WeatherForecastBDD
            WeatherForecastTDD
            WeatherForecastUI
     
    - run: |
        echo "GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}"
        echo "SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}"
        echo "AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}"
        echo "AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}"
        echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      shell: pwsh

    #- uses: ./.github/actions/ci-build

    - uses: ./.github/actions/ci-cd-dev
         