name: CI PR Action

on:
  workflow_dispatch:
 
env:
     AZURE_REGION: 'centralindia'
     RESOURCE_GROUP_NAME: 'WeatherForecastRG'
     MSI_NAME: 'WeatherForecastAppMSI'
     MSI_RESOURCE_GROUP: 'WeatherForecastRG'
     APP_NAME_PREFIX: 'WeatherForecast'
     GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
     SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}
     AZURE_CREDENTIALS : ${{secrets.AZURE_CREDENTIALS}}
      
jobs:
  ci-pr:

    runs-on: windows-latest

    steps:
  
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
      with:
        sparse-checkout: |
            .github
            Deploy
            WeatherForecastAPI
            WeatherForecastBDD
            WeatherForecastTDD
            WeatherForecastUI
     
    - run: |
        echo "GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}"
        echo "SONAR_TOKEN: ${{env.SONAR_TOKEN}}"
        echo "AZURE_CREDENTIALS: ${{env.AZURE_CREDENTIALS}}"
      shell: pwsh

    - uses: ./.github/actions/ci-build
      with:
         SOLUTION_NAME: 'WeatherForecast'
         TEST_PROJECT_PATH: 'WeatherForecastTDD\WeatherForecastTDD.csproj'
         GITHUB_TOKEN : ${{env.GITHUB_TOKEN}}
         SONAR_TOKEN : ${{env.SONAR_TOKEN}}

    - uses: ./.github/actions/ci-cd-dev
      with:
         AZURE_REGION: '${{env.AZURE_REGION}}'
         RESOURCE_GROUP_NAME: '${{env.RESOURCE_GROUP_NAME}}'
         MSI_NAME: '${{env.MSI_NAME}}'
         MSI_RESOURCE_GROUP: '${{env.MSI_RESOURCE_GROUP}}'
         APP_NAME_PREFIX: '${{env.APP_NAME_PREFIX}}'
         GITHUB_TOKEN : ${{env.GITHUB_TOKEN}}
         SONAR_TOKEN : ${{env.SONAR_TOKEN}}
         AZURE_CREDENTIALS : ${{env.AZURE_CREDENTIALS}}