name: CI PR Action

on:
  workflow_dispatch:
 
env:
     AZURE_REGION: 'centralindia'
     RESOURCE_GROUP_NAME: 'WeatherForecast-dev-rg'
     MSI_NAME: 'WeatherForecastAppMSI'
     MSI_RESOURCE_GROUP: 'WeatherForecast-dev-rg'
     APP_NAME_PREFIX: 'WeatherForecast'
     ENVIRONMENT_TYPE: 'dev'
     BICEP_FILE_PATH: 'Deploy' 
     SOLUTION_NAME: 'WeatherForecast'
     TEST_PROJECT_PATH: 'WeatherForecastTDD/WeatherForecastTDD.csproj' #for linux need to have forward slash
     GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
     SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}
     AZURE_CREDENTIALS : ${{secrets.AZURE_CREDENTIALS}}
     DOTNET_VERSION: '6.0.x' 
     FUNCTIONAPP_PATH: 'WeatherForecastAPI'
     ANGULAR_PATH: 'WeatherForecaastUI'
     NODE_VERSION: '14'
     AZURE_APP_ID: ${{ fromJSON(toJSON(env.AZURE_CREDENTIALS)).clientId }}
     AZURE_APP_SECRET: ${{ fromJSON(toJSON(env.AZURE_CREDENTIALS)).clientSecret }}

jobs:
  ci-pr:

    runs-on: ubuntu-latest

    environment: dev

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
  
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
      with:
        sparse-checkout: |
            .github
            Deploy
            WeatherForecastAPI
            WeatherForecastBDD
            WeatherForecastTDD
            WeatherForecastUI
     
    - run: |
        echo "GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}"
        echo "SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}"
        echo "AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}"
      shell: bash

    #- uses: ./.github/actions/ci-build

    - uses: ./.github/actions/ci-cd-dev
         